"""Constants for the JUDO Cloud integration."""

DOMAIN = "judo_cloud"
CONF_DEVICE_INDEX = "device_index"
DEFAULT_SCAN_INTERVAL = 300
MIN_SCAN_INTERVAL = 60

DEFAULT_SALT_USE_KG_PER_M3 = 0.4
SALT_PER_REGENERATION_KG = 0.095
SALT_TANK_CAPACITY_KG = 50.0
